apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.url }}
  password: {{ .Values.token }}
  username: {{ .Values.username }}
