apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-controllers
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/whizus/poc/kcd-platform-prototype/kcd_demo_app.git
    targetRevision: HEAD
    path: ./gitops/infra/controllers
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
