apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deployement
  name: test-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployement
  strategy: {}
  template:
    metadata:
      labels:
        app: test-deployement
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
